{
config,
lib,
pkgs,
...
}:
with lib; let
cfg = config.features.desktop.wayland;
in {
options.features.desktop.wayland.enable = mkEnableOption "wayland extra tools and config";

config = mkIf cfg.enable {
    programs.waybar = {
      enable = true;
      systemd.enable = true;
      style = ''
        /* Generated by matugen from your wallpaper, falls back to
           ./matugen/defaults/waybar-colors.css until matugen has run once.
           See matugen.nix. */
        @import url("colors.css");

        ${builtins.readFile "${pkgs.waybar}/etc/xdg/waybar/style.css"}

        window#waybar {
          background: alpha(@background, 0.85);
          border-bottom: none;
        }

        #workspaces button.active {
          background: @primary;
          color: @on-primary;
        }

        #custom-swaync {
          color: @foreground;
        }

        #custom-swaync.notification {
          color: @urgent;
        }

        * {
          ${if config.hostId == "yoga" then ''
          font-size: 18px;
        '' else ''

          ''}
        }
      '';
      settings = [{
        height = 30;
        layer = "top";
        position = "bottom";
        tray = { spacing = 10; };
        modules-center = [ "sway/window" ];
        modules-left = [ "sway/workspaces" "sway/mode" ];
        modules-right = [
          "custom/swaync"
          "pulseaudio"
          "network"
          "cpu"
          "memory"
          "temperature"
        ] ++ (if config.hostId == "yoga" then [ "battery" ] else [ ])
        ++ [
          "clock"
          "tray"
        ];
        battery = {
          format = "{capacity}% {icon}";
          format-alt = "{time} {icon}";
          format-charging = "{capacity}% ";
          format-icons = [ "" "" "" "" "" ];
          format-plugged = "{capacity}% ";
          states = {
            critical = 15;
            warning = 30;
          };
        };
        clock = {
          format-alt = "{:%Y-%m-%d}";
          tooltip-format = "{:%Y-%m-%d | %H:%M}";
        };
        cpu = {
          format = "{usage}% ";
          tooltip = false;
        };
        memory = { format = "{}% "; };
        network = {
          interval = 1;
          format-alt = "{ifname}: {ipaddr}/{cidr}";
          format-disconnected = "Disconnected ⚠";
          format-ethernet = "{ifname}: {ipaddr}/{cidr}   up: {bandwidthUpBits} down: {bandwidthDownBits}";
          format-linked = "{ifname} (No IP) ";
          format-wifi = "{essid} ({signalStrength}%) ";
        };
        pulseaudio = {
          format = "{volume}% {icon} {format_source}";
          format-bluetooth = "{volume}% {icon} {format_source}";
          format-bluetooth-muted = " {icon} {format_source}";
          format-icons = {
            car = "";
            default = [ "" "" "" ];
            handsfree = "";
            headphones = "";
            headset = "";
            phone = "";
            portable = "";
          };
          format-muted = " {format_source}";
          format-source = "{volume}% ";
          format-source-muted = "";
          on-click = "pavucontrol";
        };
        "sway/mode" = { format = ''<span style="italic">{}</span>''; };
        "custom/swaync" = {
          tooltip = true;
          tooltip-format = "Left click: notification center\nRight click: do not disturb";
          format = "{icon} {}";
          format-icons = {
            notification = " ";
            none = " ";
            dnd-notification = " ";
            dnd-none = " ";
          };
          return-type = "json";
          exec-if = "which swaync-client";
          exec = "swaync-client -swb";
          on-click = "swaync-client -t -sw";
          on-click-right = "swaync-client -d -sw";
          escape = true;
        };
        temperature = {
          critical-threshold = 80;
          format = "{temperatureC}°C {icon}";
          format-icons = [ "" "" "" ];
        };
      }];
    };

  home.packages = with pkgs; [
    grim
    hyprlock
    qt6.qtwayland
    slurp
    waypipe
    wf-recorder
    wl-mirror
    wl-clipboard
    wlogout
    wtype
    ydotool
  ];
};
}
